[package]
name = "tensr_proc_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
prettyplease = "0.2.20"
proc-macro2 = "1.0.86"
itertools = "0.13.0"

[lib]
proc-macro = true
