[package]
name = "tensr"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
rayon = "1.10.0"

[dev-dependencies]
paste = "1.0"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = 3
strip = true
debug = false
debug-assertions = false

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
# missing_docs = { level = "warn", priority = -2 }
