name: "Create Release"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
  workflow_call:

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download Rust Nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Publish to Crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Clean Source Code
        run: cargo clean

      - name: Zip Source Code
        run: |
          zip -r tensr.zip ../tensr

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            tensr.zip
            README.md
            LICENSE-MIT
            LICENSE-APACHE
